### ISSUE TITLE
UE 4.23 Support

### ISSUE THREAD

**Issue by OnlyOnePro** [UE4-OceanProject/OceanProject#109]
Just to remind that official Plugin and BP support for 4.23 isn't available. Any idea when this could arrive? I'm hyped as F for trying this in one of our projects 😊

**Comment by EvoPulseGaming** [comment]
Unless I can get some help with https://github.com/UE4-OceanProject/OceanProject/issues/110.

I have yet to find someone capable of fixing this issue for me, I've paused my work on this until then, as my work/goals on this project have become too fragmented, and I need to start closing out issues instead of moving to another aspect. The separation of the plugins will happen when the features work xD (It would cause more work to update multiple plugins when a dependent plugin is modified, this starts to become tiresome when you are trying to fix a bug, and every change requires you to re-compile another plugin)

(For now, have you tried compiling this for 4.23 as it is?)

**Comment by Przemek2122** [comment]
Hello, Ocean plugin works even better in 4.23.
Although you have to download and package plugin otherwise you won't be able to package game.

**Comment by EvoPulseGaming** [comment]
Can you explain what you mean by packaging the plug-in?

**Comment by Przemek2122** [comment]
In editor open plugins and package. Otherwise there is ApexDestruction missing.

**Comment by EvoPulseGaming** [comment]
I found it, seems in 4.7 they addex "apex cloth" to the sails... this (and most of the boats) should be removed as its not within the scope of the project. Join us on the discord channel? https://discord.gg/YtAHny

**Comment by EvoPulseGaming** [comment]
I will go ahead and add this special instruction in for 4.23

**Comment by Przemek2122** [comment]
No need for instruction just package plugin and upload it to github.

**Comment by Fearcry** [comment]
The ocean project in UE 4.23 is causing constant crash . :(

**Comment by EvoPulseGaming** [comment]
Open an new issue for this and post the crash log

**Comment by hugoar** [comment]
i didn't manage to make it work when I build. it is working in the editor but the ocean disappear in a build

**Comment by hugoar** [comment]
I would love to have the 4.23 plugin in the github

**Comment by EvoPulseGaming** [comment]
Nothing is for free, the last thing I asked for was a crash log.

**Comment by Fearcry** [comment]
[MyProject.log](https://github.com/UE4-OceanProject/OceanProject/files/3846053/MyProject.log)

**Comment by Przemek2122** [comment]
This is not readable. Could you please upload log as a file?

**Comment by EvoPulseGaming** [comment]
I've responded to the new issue he created, and as far as this issue is concerned, the project compiles fine in 4.23 without changes to the code.
