### ISSUE TITLE
4.17 Compatibility?

### ISSUE THREAD

**Issue by jBachalo** [UE4-OceanProject/OceanProject#42]
Hi
For a current AR project need to use the 4.17 build of Unreal. Can anyone tell me if theOcean Project is compatible with UE4.17?

If not, is there4 an ETA or possible alternative? Thanks!

**Comment by Truthkey** [comment]
I had no trouble using it in 4.17, but after the Update 1 of the engine tons of problems have appeared where it says some variables have invalid types.

**Comment by jBachalo** [comment]
Thanks! Anyone know how performance is on mobile?

**Comment by MichelDiz** [comment]
4.17.2 also incompatible. Fail using it.

**Comment by TheZoc** [comment]
Hello :)

Can you try my fork of it? It should support all versions of 4.17, but I haven't tried on 4.17.2 yet.

https://github.com/TheZoc/OceanProject

There's a PR open for it and, if everything is working, I'll merge it. Haven't done so yet because I'm talking with Cam about some rules on maintaining this repository.

Hope to have your feedback soon!

**Comment by FinalSparkGamestudios** [comment]
works.

**Comment by magnusroe** [comment]
Works here too! on 4.17.2.

**Comment by TheZoc** [comment]
I started some preparations to merge the PR #35 (4.17 support and fixes) , but I found a minor issue I'd like to fix appropriately before merging.
In meantime, feel free to keep using my branch, if you can't wait this time. If everything goes according to the plan, I'll probably have this done in a couple days, max 😃

**Comment by TheZoc** [comment]
I just merged the commit 075244c, which adds support to Unreal Engine 4.17!
If anything go wrong, please, let me know! 😁
