### ISSUE TITLE
Map wave modulation

### ISSUE THREAD

**Issue by senitelty** [UE4-OceanProject/OceanProject#46]
Modulation of the waves for level maps doesn't work on other levels when you build the game. maybe I'm missing something? it works on the island map, but for some reason it doesn't work for other maps.
![image](https://user-images.githubusercontent.com/7417272/31307038-cccd191c-ab64-11e7-9a60-ced4266d0121.png)

in editor it works just fine..
![image](https://user-images.githubusercontent.com/7417272/31307048-edb0b12a-ab64-11e7-964e-3af598c92017.png)

**Comment by TheZoc** [comment]
Hello @senitelty :)

I saw you attempted to send me a message in UE4 forums, but I can't read the full message... I just knew because I got an email notification.

Isn't that caused because of the wave height?
Do you mind trying with different blueprints? Copy and paste different ones from example maps, might give us additional info about this issue :)

I'd love of you could report back with your findings! :D

**Comment by senitelty** [comment]
Hi @TheZoc :)
Thanks for the response and sorry it took me so long to respond. Ok so I found the problem, it appears that the numbers corresponding to the modulation work in a very strange way. For example if you have a map that is farely not high then it for some reason needs the modulation start height to be very low like -27 000.... no idea why, but it works now... here is the ocean map setup i used to reproduce try it maybe i'm just not understanding something... 
https://www.dropbox.com/s/a9qf7prhzcye73t/OceanHeightTest.zip?dl=0

**Comment by TheZoc** [comment]
@senitelty Sorry I wasn't able to reply before, things have been very busy on my side.
Were you able to find the reason of all of that?

I'm wondering why this only happens when building the game, but works fine in the editor...
