### ISSUE TITLE
How to change Day/Night Cycle duration?

### ISSUE THREAD

**Issue by themartiano** [UE4-OceanProject/OceanProject#52]
The Day/Night Cycle System have a duration of 24hrs. Where i can change the duration time? Thank You!!
:3

**Comment by TheZoc** [comment]
I'm not sure, but I think you will need to give deep into that code.

I remember changing something recently about a time manager in the code... Not sure if it helps to check the latest commits.

I hope this helps you :)

**Comment by themartiano** [comment]
Ok, ty for help! 👍 :)

**Comment by TheZoc** [comment]
@EduardoJMartinez PR #58 was just merged. This probably helps with your question! 😉

**Comment by dotcamdev** [comment]
Custom day length is something I want to support, but wasn't able to implement when I worked on it last. 

Will look into it for a future release.

**Comment by dotcamdev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support Custom Day, Month, and Year Durations](https://trello.com/c/zsYD9icr/58-support-custom-day-month-and-year-durations)

**Comment by MakotoIchinose** [comment]
Actually you can just multiply the delta seconds in Update Time of Day function with the built in Time Scale Multiplier variable.
![Capture](https://user-images.githubusercontent.com/26211033/55669347-6db37580-58a0-11e9-91d1-6f49f0cf1855.JPG)
This trick works everytime, and I able to scale the in-game time to 2 seconds / 1 in-game minute.

Now, I think you can still take this trick with a grain of salt, since it requires simple trick to solve yet this issue thread is still open.

**Comment by EvoPulseGaming** [comment]
Man, I really wish I had time to get back into this project
If you go to the ocean project homepage, there is a timer manager plugin I created.
Its with full blueprint support!
This will auto inject a TimerManager actor into ANY map automatically, but if you manually place one, it wont. This is neat because you can "override" the defaults, or just let the default auto spawn.
Note: Once you save the map with the AutoInjected TimerManager, any changes will save with the map!

However, you will want to remove the old TimerManager from the c++ code.

Also unreal engine now has built in support for sun position calculations, that are probably more accurate than what we have, so I will have to convert everything over to the new system some time...

**Comment by EvoPulseGaming** [comment]
So it turns out that ue4's built in sun position plugin is actually not 100% correct, i've already fixed this in the diftow branch, the time stuff is also ready in the main branch but hasn't replaced the old one. I'm closing this as all of these fixes are about to be released in the next week or two
