### ISSUE TITLE
Transparency issue2 (With Particle Effect)

### ISSUE THREAD

**Issue by BHSUnreal** [UE4-OceanProject/OceanProject#53]
How do you render effects before water?
Thank you,

![error](https://user-images.githubusercontent.com/31195554/32671595-5da86a5e-c68b-11e7-9475-2c07b7c72d60.png)

**Comment by TheZoc** [comment]
I'm not sure I follow your issue... Effects are being rendered before the water, hence their reflexin water. Is there anything missing?

**Comment by BHSUnreal** [comment]
Put ShipAndExamples/Cannonz/Particle/P_FireOptimized particle  to oceanEXample_01.map.
you can see same issue. 
thanks fot your reply :)

**Comment by MariusGr** [comment]
I have this very same issue. All translucent materials are not showing up, when the the ocean plane is behind. This might be caused by the translucent material of the ocean plane itself to chancel out the rendering of any other translucent material in the same screen space.

Hence the wake effect is completely invisible as well as all my particle effects on the water.

The attached image shows a comparison between the same incident (cannon ball hits the water surface and spawns splash effect, which consists of translucent particles) with and without modification of OceanPlane's Translucency Sort Priority.
Changing this it to -1 is a temporary workaround, but also causes particles underwater still to appear as if they were above.

I also noticed that the explosion effects you use when the cannons are being fired has the same issue, but only with certain camera angles.

![oceantranslucencyissue01](https://user-images.githubusercontent.com/12848259/35581196-62ed33ec-05eb-11e8-97b7-2eae774bcca2.jpg)

**Comment by BHSUnreal** [comment]
Thanks fo your reply MariusGr.
It is a temporary method, but it will help a lot.

**Comment by dotcamdev** [comment]
Merging this issue with the other transparency issue (#51) as they are related.

**Comment by dotcamdev** [comment]
#51

**Comment by dotcamdev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Transparent Object Issue with Ocean in Level](https://trello.com/c/Ws55P2UZ/65-transparent-object-issue-with-ocean-in-level)

**Comment by EvoPulseGaming** [comment]
Don't believe this is an issue any more.
