### ISSUE TITLE
BP_Sky "Is Static" Feature

### ISSUE THREAD

**Issue by reapazor** [UE4-OceanProject/OceanProject#64]
I implemented this at the blueprint level by adding to the beginplay/tick/construct checking for movability flags on the lights and just preventing any actual updates happening if they were not all set to movable. Allowed for custom time of day, with baked lights.

Just an idea - will look at a PR when done with project.

**Comment by TheZoc** [comment]
Thank you! I'm looking forward to merge this!

**Comment by reapazor** [comment]
Heh I actually changed the blueprint quite a bit ... um i'll figure a way to get it to you ...but it works great ...lets me set it, bake, and still use everything :)

**Comment by TheZoc** [comment]
Any news? :)

**Comment by reapazor** [comment]
So I ended up going non static again, im trying to figure out how to get this to you … I might just zip up my bp’s etc … a PR isn’t as simple because I hacked in external stuff as well ;/

--
Matthew Davey
dotBunny

**Comment by TheZoc** [comment]
Try using the "export" feature to a blank project (Im not sure about the name of the feature, on cellphone right now - it allows you to send an asset and all dependencies to another project).
This way you can check if you have something you don't want to share, from your project) or if there is a mistakenly included asset as dependency :)

But, Ofc, we're not in a hurry, so take your time :))

**Comment by dotcamdev** [comment]
Sorry I couldn't answer you sooner, but this looks like a good idea to me!

You don't need to bother creating a PR for this, I have a lot of work to do fixing the skydome so I will just add it to my list! 

Just to confirm, you want to have a check performed to look for non-movable lights in the level, and if so prevent any updating of the sky, then bake out the lights and then keep the sun stationary at that position, correct?

There may even be a way to bake out multiple points throughout the day/night that you could then switch to later during gameplay (daytime when you enter a house, nighttime when you leave).

That would be a very interesting idea, I might create a separate skydome for people wanting to use stationary/static lights though since the two methods require completely different settings.

I will add that quick fix you posted above in the second Cleanup update coming on the weekend, and look into implementing the second skydome in the near future. (to make this easier I am going to add this to Trello rather than use this github issue, I will post a link to it shortly)

Thanks!

**Comment by dotcamdev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Static Lighting for Skydome](https://trello.com/c/NjJoPE78/59-static-lighting-for-skydome)

**Comment by EvoPulseGaming** [comment]
Since this was taken over by dotcam, and he doesn't appear to be with us any longer I will close this out.
