### ISSUE TITLE
Trello not updated anymore?

### ISSUE THREAD

**Issue by P1llus** [UE4-OceanProject/OceanProject#71]
Hey guys!

I haven't been following this project for a while, and i noticed that the Trello board is not been updated since 2015, but the link is still in the Github Readme, is this correct?

Could anyone tell me about if there is currently any ongoing activity here?

I saw that most commits for this year is just to add functionality for newer Unreal versions.

If there is still activity here, i could always produce some PR's :)

**Comment by EvoPulseGaming** [comment]
Of course this is active, we could always use PR's, there was a recent push to update this and VaOcean to 4.19, and also determine the license status of VaOcean (missing Nvidia license) so the next step was to merge the two projects, however there are around 3 different people doing their own version of an fft ocean so the merge will wait a bit for results

**Comment by P1llus** [comment]
@saschaelble Thanks for the response, was just a bit unsure when i saw the Trello board so :) If it is not in use anymore, maybe it should be removed from the github readme?

On terms of 4.19, i did try to use that project in 4.19, but ended up with the same issues as #55, mentioned in my issue #72 

Do you know anything about that?

**Comment by EvoPulseGaming** [comment]
I don't. I do know I've compiled it for 4.19 without issues before. Not
sure what changed. Do note that the maintainer likes to commit code changes
separately from binary changes (dlls)

**Comment by P1llus** [comment]
When saying compiled i'm a bit confused. The reason is that i tried to load the project in both 4.17, 4.18 and 4.19. By either just opening uproject directly, or opening the editor and importing the project, and i would just get the same issues with compiling those two dll's :( So you must be importing it differently i guess.

**Comment by TheZoc** [comment]
@P1llus The base project file was wrong, sadly. I pushed the commit and updated #72 :)

About Trello, it isn't updated for a while, indeed. I do not have write access to it, so we will need to wait on @dotcamdev until he's ready to come back :)

The project is active and I'm making sure it's compatible with UE4 latest releases... Previously, it would be weeks before an update was pushed - if it was updated at all - and you'd need to rely either on updating yourself or searching through one of the numerous GitHub forks. I used to post in UE4 topic whenever I updated it, so hopefully I could help other people.

Sadly, I'm not an experienced shader developer, so there were some regressions (Mainly #51 and #53) due to internal changes in UE4. Of course, we're open for Pull Requests, and I really appreciate contributions to this project. After all, if someone can fix it, everyone that is following/using this project can enjoy the fix 😁 

And I apologize for not being able to check the PR's right away, there's a lot going on in RL atm, but rest assured I"m doing my best to keep this project up to date!

**Comment by P1llus** [comment]
Hello @TheZoc :)

Thank you for answering all my questions and so on! Feel free to close this issue to remove it from the open issue list.

Good to see that there is still people working on this. Is there specific work that might need more attention than others?

**Comment by TheZoc** [comment]
@P1llus I think #51 and #53 (possibly duplicates) are our main concern right now. If you're willing to check Trello for improvements, the help would be very much welcome! :D

**Comment by dotcamdev** [comment]
Hey guys, I'm back :)

Before I begin updating Trello, I need to do some work on fixing bugs and documenting various blueprints and materials (as well as general documentation). I'm working on that now, once complete I will check Trello and add more people to it with write access. Stay tuned!

**Comment by dotcamdev** [comment]
Alright, Trello is back. There is still some cleanup needed, but we will start using it again. 
Thanks!
