### ISSUE TITLE
Mac UE 4.19.2

### ISSUE THREAD

**Issue by bdark** [UE4-OceanProject/OceanProject#80]
HI is there a way to open it the project on a Mac? 
It comes always with the error:

The following modules are missing or built with a different engine version:

UE4Editor-OceanProject.dylib
UE4Editor-OceanPlugin.dylib

Would you like to rebuild them now?

**Comment by NilsonFLima** [comment]
Whenever opening a project and you have such question, means you need to rebuild the component. All files at the repository are usually compiled in Windows, therefore it will be needed always to have them recompiled(rebuild). I don't have a Mac to test this, but it would require you to understand how to deal with compiling plugins in order to know what is happening. This is a C++ plugin project and not a simple Blueprint project. Join us on Discord (see latest thread posts for the link).

**Comment by EvoPulseGaming** [comment]
This appears to have been solved. Knowledge for building ue4 projects is required
