### ISSUE TITLE
Solving an N Wave Problem

### ISSUE THREAD

**Issue by calben** [UE4-OceanProject/OceanProject#9]
OceanProject is, as far as I can see, currently set up to solve an 8 wave problem maximum.

It may be best to modify the code so that it either solves an 8 wave + an N wave problem or so that it solves only an N wave problem.
Creating an N wave problem will allow easier faking of features such as whirlpools, wakes, and spontaneous waves from some point.

Would there be a better way of adding waves to the system?
Perhaps it should be done by adding another wave set parameter to the system, but I don't think that 2 wave set parameters can directly interact right now.

**Comment by Nsomnia** [comment]
I'll be digging heavily into this kind've stuff for my subsim game as time goes on and my knowledge of cpp and ue4's api increases

**Comment by tk-master** [comment]
The C++ part could be modified to solve as many gerstner waves as the user wants but the material side is a different story! there is no support for arrays or for-loops and so the number of waves have to be pre-defined in the shader.
We actually had 16 waves before but DotCam disabled the second cluster since it's wasn't making a huge visual difference anyway and the performance boost is probably worth it IMO.

That said, it is already possible to enable the 16 wave mode by enabling the second cluster from the material instance (but there are no configs for the second cluster in the blueprint or C++ so you will have to edit the code a bit).

And btw about whirlpools and wakes.. I really don't think you can make those with gerstner waves, those need a method of their own.

At the end of the day the gerstner wave system that we currently have is only a temporary solution so unless your project requires this soon then I would not bother too much with it, we will have an FFT system eventually which will be easily configurable via Beaufort scale (it's only a matter of time really).
