### ISSUE TITLE
Unreal Engine 4.21 support

### ISSUE THREAD

**Issue by BoiseComputer** [UE4-OceanProject/OceanProject#94]
Would like updates to allow compiling for Unreal Engine 4.21.

**Comment by NilsonFLima** [comment]
I have just made a branch with 4.21 set over there. I will only update the project in this branch, so be sure to get from it. https://github.com/UE4-OceanProject/OceanProject/tree/OceanProjectNilsonLima

**Comment by Beerbill** [comment]
Still having problems using that versions, BP_Ocean won't exist in version 4.21, the linked version won't work. I got an older commit before the upgrade for 4.22 and it's working fine.

Thanks.

**Comment by NilsonFLima** [comment]
If you got the 4.22 it won't work in 4.21 and since the 4.22 will release next week from this date, is not bad. There will be significant changes coming in 4.23 that will require changes in the source code. There is a huge performance improvement on materials in general and I recommend anyone that is starting a game development, that uses 4.22 instead of previous stable versions. If the development is too advanced then no.

**Comment by EvoPulseGaming** [comment]
I try to keep this updated with NilsonFLima's fork, and any other improvements found in other forks. Updated it a not long ago to his latest at the time
